export const htmlcssnavitems = [
  {
    name: "HTML",
    tutorial: true,
    ref: true,
  },
  {
    name: "CSS",
    tutorial: true,
    ref: true,
  },
  {
    name: "RWD",
    tutorial: true,
    ref: false,
  },
  {
    name: "Bootstrap",
    tutorial: false,
    ref: true,
    overview: true,
  },
  {
    name: "W3.CSS",
    tutorial: true,
    ref: true,
  },
  {
    name: "SASS",
    tutorial: true,
    ref: true,
  },
  {
    name: "Colors",
    tutorial: true,
    ref: true,
  },
  {
    name: "Icons",
    tutorial: true,
    ref: true,
  },
  {
    name: "SVG",
    tutorial: true,
    ref: true,
  },
  {
    name: "Canvas",
    tutorial: true,
    ref: true,
  },
  {
    name: "Graphics",
    tutorial: true,
    ref: false,
  },
];

export const jsitems = [
  {
    name: "JavaScript",
    tutorial: true,
    ref: true,
  },
  {
    name: "React",
    tutorial: true,
    ref: false,
  },
  {
    name: "jQuery",
    tutorial: true,
    ref: true,
  },
  {
    name: "Vue",
    tutorial: true,
    ref: true,
  },
  {
    name: "Angular JS",
    tutorial: true,
    ref: true,
  },
  {
    name: "JSON",
    tutorial: true,
    ref: true,
  },
  {
    name: "AJAX",
    tutorial: true,
    ref: false,
  },
  {
    name: "W3.JS",
    tutorial: true,
    ref: true,
  },
  {
    name: "AppML",
    tutorial: true,
    ref: true,
  },
];

export const backenditems = [
  {
    name: "Python",
    tutorial: true,
    ref: true,
  },
  {
    name: "SQL",
    tutorial: true,
    ref: false,
  },
  {
    name: "MySQL",
    tutorial: true,
    ref: true,
  },
  {
    name: "PHP",
    tutorial: true,
    ref: true,
  },
  {
    name: "JAVA",
    tutorial: true,
    ref: true,
  },
  {
    name: "C",
    tutorial: true,
    ref: false,
  },
  {
    name: "C++",
    tutorial: true,
    ref: false,
  },
  {
    name: "C#",
    tutorial: true,
    ref: false,
  },
  {
    name: "R",
    tutorial: true,
    ref: false,
  },
  {
    name: "Kotlin",
    tutorial: true,
    ref: false,
  },
  {
    name: "Go",
    tutorial: true,
    ref: false,
  },
  {
    name: "JSON",
    tutorial: true,
    ref: true,
  },
  {
    name: "Django",
    tutorial: true,
    ref: true,
  },
  {
    name: "PostgreSQL",
    tutorial: true,
    ref: true,
  },
  {
    name: "TypeScript",
    tutorial: true,
    ref: true,
  },
  {
    name: "ASP",
    tutorial: true,
    ref: true,
  },
  {
    name: "Node.js",
    tutorial: true,
    ref: true,
  },
  {
    name: "RaspberryPi",
    tutorial: true,
    ref: false,
  },
  {
    name: "Git",
    tutorial: true,
    ref: false,
  },
  {
    name: "MongoDB",
    tutorial: true,
    ref: false,
  },
  {
    name: "AWS",
    tutorial: true,
    ref: false,
  },
  {
    name: "XML",
    tutorial: true,
    ref: true,
  },
];

export const backendCertified = [
  {
    name: "Python",
    certificate: true,
    course: true,
    bootcamp: true,
  },
  {
    name: "SQL",
    certificate: true,
    course: true,
    bootcamp: true,
  },
  {
    name: "MySQL",
    certificate: true,
    course: false,
    bootcamp: false,
  },
  {
    name: "PHP",
    certificate: true,
    course: true,
    bootcamp: false,
  },
  {
    name: "JAVA",
    certificate: true,
    course: true,
    bootcamp: false,
  },
  {
    name: "C",
    certificate: true,
    course: true,
    bootcamp: false,
  },
  {
    name: "C++",
    certificate: true,
    course: true,
    bootcamp: false,
  },
  {
    name: "C#",
    certificate: true,
    course: true,
    bootcamp: false,
  },
  {
    name: "R",
    certificate: true,
    course: false,
    bootcamp: false,
  },
  {
    name: "Django",
    certificate: true,
    course: false,
    bootcamp: false,
  },
  {
    name: "TypeScript",
    certificate: true,
    course: true,
    bootcamp: false,
  },
  {
    name: "XML",
    certificate: true,
    course: true,
    bootcamp: false,
  },
  {
    name: "Cyber Security",
    certificate: true,
    course: true,
    bootcamp: false,
  },
  {
    name: "Accessibility",
    certificate: true,
    course: true,
    bootcamp: false,
  },
  {
    name: "Python Apps on AWS",
    certificate: false,
    course: true,
    bootcamp: false,
  },

  {
    name: "AWS Training",
    certificate: false,
    course: true,
    bootcamp: false,
  },
];

export const dataitems = [
  {
    name: "AI",
    tutorial: true,
  },
  {
    name: "Generative AI",
    tutorial: true,
  },
  {
    name: "ChatGPT-3.5",
    tutorial: true,
  },
  {
    name: "ChatGPT-4",
    tutorial: true,
  },
  {
    name: "Google Bard",
    tutorial: true,
  },
  {
    name: "Machine Learning",
    tutorial: true,
  },
  {
    name: "NumPy",
    tutorial: true,
  },
  {
    name: "Pandas",
    tutorial: true,
  },
  {
    name: "SciPy",
    tutorial: true,
  },
  {
    name: "Matplotlib",
    tutorial: true,
  },
  {
    name: "Statistics",
    tutorial: true,
  },
  {
    name: "Exel",
    tutorial: true,
  },
  {
    name: "Google Sheets",
    tutorial: true,
  },
];

export const webitems = [
  { name: "Create a Website ", hot: true },
  { name: "Create a Server", new: true },
  { name: "Where To Start" },
  { name: "Web Templates" },
  { name: "Web Statistics" },
  { name: "Web Certificates" },
  { name: "Web Development" },
  { name: "Code Editor" },
  { name: "Test Your Typing Speed" },
  { name: "Play a Code Game" },
  { name: "Cyber Security" },
  { name: "Accessibility" },
  { name: "Join our Newsletter" },
];

export const htmlcssexercises = [
  {
    name: "HTML",
    exercise: true,
    quiz: true,
  },
  {
    name: "CSS",
    exercise: true,
    quiz: true,
  },
  {
    name: "Bootstrap",
    exercise: true,
    quiz: true,
  },
];

export const htmlcsscertified = [
  {
    name: "HTML",
    certificate: true,
    course: true,
    bootcamp: true,
  },
  {
    name: "CSS",
    certificate: true,
    course: true,
    bootcamp: true,
  },
  {
    name: "Bootstrap",
    certificate: true,
    course: true,
    bootcamp: false,
  },
];

export const jsexercises = [
  {
    name: "JavaScript",
    exercise: true,
    quiz: true,
  },
  {
    name: "React",
    exercise: true,
    quiz: true,
  },
  {
    name: "jQuery",
    exercise: true,
    quiz: true,
  },
  {
    name: "Vue",
    exercise: true,
    quiz: true,
  },
];

export const jscertified = [
  {
    name: "JavaScript",
    certificate: true,
    course: true,
    bootcamp: true,
  },
  {
    name: "React",
    certificate: true,
    course: true,
    bootcamp: false,
  },
  {
    name: "jQuery",
    certificate: true,
    course: true,
    bootcamp: false,
  },
  {
    name: "Vue",
    certificate: true,
    course: false,
    bootcamp: false,
  },
];

export const dataexercises = [
  {
    name: "NumPy",
    exercise: true,
    quiz: true,
  },
  {
    name: "Pandas",
    exercise: true,
    quiz: true,
  },
  {
    name: "SciPy",
    exercise: true,
    quiz: true,
  },
  {
    name: "Exel",
    exercise: true,
    quiz: false,
  },
];

export const programs = [
  {
    name: "Full Acess",
    bestValue: true,
    certificate: false,
    course: false,
  },

  {
    name: "Front End",
    bestValue: false,
    certificate: true,
    course: true,
  },
  {
    name: "Web Dev.",
    bestValue: false,
    certificate: true,
    course: true,
  },
  {
    name: "Web Design",
    bestValue: false,
    certificate: true,
    course: true,
  },
];

export const leftSidebarItems1 = [
  "HTML HOME",
  "HTML Introduction",
  "HTML Editors",
  "HTML Basic",
  "HTML Elements",
  "HTML Attributes",
  "HTML Headings",
  "HTML Paragraphs",
  "HTML Styles",
  "HTML Formatting",
  "HTML Quotations",
  "HTML Comments",
  "HTML Colors",
  "HTML CSS",
  "HTML Links",
  "HTML Images",
  "HTML Favicon",
  "HTML Page Title",
  "HTML Tables",
  "HTML Lists",
  "HTML Block & Inline",
  "HTML Classes",
  "HTML Id",
  "HTML Iframes",
  "HTML JavaScript",
  "HTML File Paths",
  "HTML Head",
  "HTML Layout",
  "HTML Responsive",
  "HTML Computercode",
  "HTML Semantics",
  "HTML Style Guide",
  "HTML Entities",
  "HTML Symbols",
  "HTML Emojis",
  "HTML Charset",
  "HTML URL Encode",
  "HTML vs. XHTML",
];

export const leftSidebarItems2 = [
  "HTML Forms",
  "HTML Form Attributes",
  "HTML Form Elements",
  "HTML Input Types",
  "HTML Input Attributes",
  "HTML Input Form Attributes",
];

export const leftSidebarItems3 = [
  "HTML Tag List",
  "HTML Attributes",
  "HTML Global Attributes",
  "HTML Browser Support",
  "HTML Events",
  "HTML Colors",
  "HTML Canvas",
  "HTML Audio/Video",
  "HTML Doctypes",
  "HTML Character Sets",
  "HTML URL Encode",
  "HTML Lang Codes",
  "HTTP Messages",
  "HTTP Methods",
  "PX to EM Converter",
  "Keyboard Shortcuts",
];

export const htmlReferences = [
  "HTML Elements",
  "Browser Support",
  "Attributes",
  "Global Attributes",
  "Event Attributes",
  "Color Names",
  "Canvas",
  "Audio/Video DOM",
  "Character Sets",
  "URL Encoding",
  "Language Codes",
  "Country Codes",
  "HTTP Messages",
  "Px to Em Converter",
  "Keyboard Shortcuts",
];

export const cssleftsidebaritems1 = [
  "CSS HOME",
  "CSS Introduction",
  "CSS Syntax",
  "CSS Selectors",
  "CSS How To",
  "CSS Comments",
  "CSS Colors",
  "CSS Backgrounds",
  "CSS Borders",
  "CSS Margins",
  "CSS Padding",
  "CSS Height/Width",
  "CSS Box Model",
  "CSS Outline",
  "CSS Text",
  "CSS Fonts",
  "CSS Icons",
  "CSS Links",
  "CSS Lists",
  "CSS Tables",
  "CSS Display",
  "CSS Max-width",
  "CSS Position",
  "CSS Z-index",
  "CSS Overflow",
  "CSS Float",
  "CSS Inline-block",
  "CSS Align",
  "CSS Combinators",
  "CSS Pseudo-class",
  "CSS Pseudo-element",
  "CSS Opacity",
  "CSS Navigation Bar",
  "CSS Dropdowns",
  "CSS Image Gallery",
  "CSS Image Sprites",
  "CSS Attr Selectors",
  "CSS Forms",
  "CSS Counters",
  "CSS Website Layout",
  "CSS Units",
  "CSS Specificity",
  "CSS !important",
  "CSS Math Functions",
];

export const cssleftsidebaritems2 = [
  "CSS Rounded Corners",
  "CSS Border Images",
  "CSS Backgrounds",
  "CSS Colors",
  "CSS Color Keywords",
  "CSS Gradients",
  "CSS Shadows",
  "CSS Text Effects",
  "CSS Web Fonts",
  "CSS 2D Transforms",
  "CSS 3D Transforms",
  "CSS Transitions",
  "CSS Animations",
  "CSS Tooltips",
  "CSS Style Images",
  "CSS Image Reflection",
  "CSS object-fit",
  "CSS object-position",
  "CSS Masking",
  "CSS Buttons",
  "CSS Pagination",
  "CSS Multiple Columns",
  "CSS User Interface",
  "CSS Variables",
  "CSS Box Sizing",
  "CSS Media Queries",
  "CSS MQ Examples",
  "CSS Flexbox",
];

export const cssleftsidebaritems3 = [
  "RWD Intro",
  "RWD Viewport",
  "RWD Grid View",
  "RWD Media Queries",
  "RWD Images",
  "RWD Videos",
  "RWD Frameworks",
  "RWD Templates",
  "CSS Grid",
  "Grid Intro",
  "Grid Container",
  "Grid Item",
  "CSS SASS",
  "SASS Tutorial",
  "CSS Examples",
  "CSS Templates",
  "CSS Examples",
  "CSS Editor",
  "CSS Snippets",
  "CSS Quiz",
  "CSS Exercises",
  "CSS Bootcamp",
  "CSS Certificate",
  "CSS References",
  "CSS Reference",
  "CSS Selectors",
  "CSS Functions",
  "CSS Reference Aural",
  "CSS Web Safe Fonts",
  "CSS Animatable",
  "CSS Units",
  "CSS PX-EM Converter",
  "CSS Colors",
  "CSS Color Values",
  "CSS Default Values",
  "CSS Browser Support",
];

export const cssreferences = [
  "CSS Properties",
  "CSS Selectors",
  "CSS Browser Support",
  "CSS Functions",
  "CSS Animatable",
  "CSS Aural",
  "CSS Web Safe Fonts",
  "CSS Units",
  "Px to Em Conversion",
  "CSS Colors",
  "CSS Default Values",
  "CSS Entities",
];

export const jsleftsidebaritems1 = [
  "JS HOME",
  "JS Introduction",
  "JS Where To",
  "JS Output",
  "JS Statements",
  "JS Syntax",
  "JS Comments",
  "JS Variables",
  "JS Let",
  "JS Const",
  "JS Operators",
  "JS Arithmetic",
  "JS Assignment",
  "JS Data Types",
  "JS Functions",
  "JS Objects",
  "JS Events",
  "JS Strings",
  "JS String Methods",
  "JS String Search",
  "JS String Templates",
  "JS Numbers",
  "JS BigInt",
  "JS Number Methods",
  "JS Number Properties",
  "JS Arrays",
  "JS Array Methods",
  "JS Array Sort",
  "JS Array Iteration",
  "JS Array Const",
  "JS Dates",
  "JS Date Formats",
  "JS Date Get Methods",
  "JS Date Set Methods",
  "JS Math",
  "JS Random",
  "JS Booleans",
  "JS Comparisons",
  "JS If Else",
  "JS Switch",
  "JS Loop For",
  "JS Loop For In",
  "JS Loop For Of",
  "JS Loop While",
  "JS Break",
  "JS Iterables",
  "JS Sets",
  "JS Maps",
  "JS Typeof",
  "JS Type Conversion",
  "JS Bitwise",
  "JS RegExp",
  "JS Precedence",
  "JS Errors",
  "JS Scope",
  "JS Hoisting",
  "JS Strict Mode",
  "JS this Keyword",
  "JS Arrow Function",
  "JS Classes",
  "JS Modules",
  "JS JSON",
  "JS Debugging",
  "JS Style Guide",
  "JS Best Practices",
  "JS Mistakes",
  "JS Performance",
  "JS Reserved Words",
];

export const jsleftsidebaritems2 = [
  "DOM Intro",
  "DOM Methods",
  "DOM Document",
  "DOM Elements",
  "DOM HTML",
  "DOM Forms",
  "DOM CSS",
  "DOM Animations",
  "DOM Events",
  "DOM Event Listener",
  "DOM Navigation",
  "DOM Nodes",
  "DOM Collections",
  "DOM Node Lists",
];

export const jsleftsidebaritems3 = [
  "JS Window",
  "JS Screen",
  "JS Location",
  "JS History",
  "JS Navigator",
  "JS Popup Alert",
  "JS Timing",
  "JS Cookies",
  "JS Web APIs",
  "Web API Intro",
  "Web Forms API",
  "Web History API",
  "Web Storage API",
  "Web Worker API",
  "Web Fetch API",
  "Web Geolocation API",
  "JS AJAX",
  "AJAX Intro",
  "AJAX XMLHttp",
  "AJAX Request",
  "AJAX Response",
  "AJAX XML File",
  "AJAX PHP",
  "AJAX ASP",
  "AJAX Database",
  "AJAX Applications",
  "AJAX Examples",
  "JS JSON",
  "JSON Intro",
  "JSON Syntax",
  "JSON vs XML",
  "JSON Data Types",
  "JSON Parse",
  "JSON Stringify",
  "JSON Objects",
  "JSON Arrays",
  "JSON Server",
  "JSON PHP",
  "JSON HTML",
  "JSON JSONP",
];

export const sqlleftsidebaritems1 = [
  "SQL Intro",
  "SQL Syntax",
  "SQL Select",
  "SQL Select Distinct",
  "SQL Where",
  "SQL Order By",
  "SQL And",
  "SQL Or",
  "SQL Not",
  "SQL Insert Into",
  "SQL Null Values",
  "SQL Update",
  "SQL Delete",
  "SQL Select Top",
  "SQL Min and Max",
  "SQL Count",
  "SQL Sum",
  "SQL Avg",
  "SQL Like",
  "SQL Wildcards",
  "SQL In",
  "SQL Between",
  "SQL Aliases",
  "SQL Joins",
  "SQL Inner Join",
  "SQL Left Join",
  "SQL Right Join",
  "SQL Full Join",
  "SQL Self Join",
  "SQL Union",
  "SQL Group By",
  "SQL Having",
  "SQL Exists",
  "SQL Any, All",
  "SQL Select Into",
  "SQL Insert Into Select",
  "SQL Case",
  "SQL Null Functions",
  "SQL Stored Procedures",
  "SQL Comments",
  "SQL Operators",
];

export const sqlleftsidebaritems2 = [
  "SQL Create DB",
  "SQL Drop DB",
  "SQL Backup DB",
  "SQL Create Table",
  "SQL Drop Table",
  "SQL Alter Table",
  "SQL Constraints",
  "SQL Not Null",
  "SQL Unique",
  "SQL Primary Key",
  "SQL Foreign Key",
  "SQL Check",
  "SQL Default",
  "SQL Index",
  "SQL Auto Increment",
  "SQL Dates",
  "SQL Views",
  "SQL Injection",
  "SQL Hosting",
  "SQL Data Types",
];

export const sqlleftsidebaritems3 = [
  "SQL Keywords",
  "MySQL Functions",
  "SQL Server Functions",
  "MS Access Functions",
  "SQL Quick Ref",
  "SQL Examples",
  "SQL Examples",
  "SQL Editor",
  "SQL Quiz",
  "SQL Exercises",
  "SQL Bootcamp",
  "SQL Certificate",
];

export const sqlreferences = [
  "SQL Keyword Reference",

  "MYSQL Functions",

  "SQLServer Functions",

  "MS Access Functions",

  "SQL Quick Reference",
];
